# Polars


Импортируем polaris и читаем наш DataFrame

In [59]:
import polars as pl

df = pl.read_csv("train.csv")
df.head(10)

shape: (10, 12)
┌─────────────┬──────────┬────────┬───────────────────┬───┬───────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name              ┆ … ┆ Ticket    ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---               ┆   ┆ ---       ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str               ┆   ┆ str       ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪═══════════════════╪═══╪═══════════╪═════════╪═══════╪══════════╡
│ 1           ┆ 0        ┆ 3      ┆ Braund, Mr. Owen  ┆ … ┆ A/5 21171 ┆ 7.25    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Harris            ┆   ┆           ┆         ┆       ┆          │
│ 2           ┆ 1        ┆ 1      ┆ Cumings, Mrs.     ┆ … ┆ PC 17599  ┆ 71.2833 ┆ C85   ┆ C        │
│             ┆          ┆        ┆ John Bradley (Fl… ┆   ┆           ┆         ┆       ┆          │
│ 3           ┆ 1        ┆ 3      ┆ Heikkinen, Miss.  ┆ … ┆ STON/O2.  ┆ 7.925   ┆ null  ┆ S        │
│             ┆          ┆        ┆ Laina             ┆   ┆ 3101282   ┆         ┆       ┆          │
│ 4           ┆ 1        ┆ 1      ┆ Futrelle, Mrs.    ┆ … ┆ 113803    ┆ 53.1    ┆ C123  ┆ S        │
│             ┆          ┆        ┆ Jacques Heath (…  ┆   ┆           ┆         ┆       ┆          │
│ 5           ┆ 0        ┆ 3      ┆ Allen, Mr.        ┆ … ┆ 373450    ┆ 8.05    ┆ null  ┆ S        │
│             ┆          ┆        ┆ William Henry     ┆   ┆           ┆         ┆       ┆          │
│ 6           ┆ 0        ┆ 3      ┆ Moran, Mr. James  ┆ … ┆ 330877    ┆ 8.4583  ┆ null  ┆ Q        │
│ 7           ┆ 0        ┆ 1      ┆ McCarthy, Mr.     ┆ … ┆ 17463     ┆ 51.8625 ┆ E46   ┆ S        │
│             ┆          ┆        ┆ Timothy J         ┆   ┆           ┆         ┆       ┆          │
│ 8           ┆ 0        ┆ 3      ┆ Palsson, Master.  ┆ … ┆ 349909    ┆ 21.075  ┆ null  ┆ S        │
│             ┆          ┆        ┆ Gosta Leonard     ┆   ┆           ┆         ┆       ┆          │
│ 9           ┆ 1        ┆ 3      ┆ Johnson, Mrs.     ┆ … ┆ 347742    ┆ 11.1333 ┆ null  ┆ S        │
│             ┆          ┆        ┆ Oscar W (Elisabe… ┆   ┆           ┆         ┆       ┆          │
│ 10          ┆ 1        ┆ 2      ┆ Nasser, Mrs.      ┆ … ┆ 237736    ┆ 30.0708 ┆ null  ┆ C        │
│             ┆          ┆        ┆ Nicholas (Adele   ┆   ┆           ┆         ┆       ┆          │
│             ┆          ┆        ┆ A…                ┆   ┆           ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴───────────────────┴───┴───────────┴─────────┴───────┴──────────┘

Выводим основную информацию о датасете: информацию о типах данных, число пропусков, средние значения и т.д.

In [60]:
df.describe()

shape: (9, 13)
┌────────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────┬──────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ Ticket    ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---      │
│ str        ┆ f64         ┆ f64      ┆ f64      ┆   ┆ str       ┆ f64       ┆ str   ┆ str      │
╞════════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════╪══════════╡
│ count      ┆ 891.0       ┆ 891.0    ┆ 891.0    ┆ … ┆ 891       ┆ 891.0     ┆ 204   ┆ 889      │
│ null_count ┆ 0.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0       ┆ 687   ┆ 2        │
│ mean       ┆ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ … ┆ null      ┆ 32.204208 ┆ null  ┆ null     │
│ std        ┆ 257.353842  ┆ 0.486592 ┆ 0.836071 ┆ … ┆ null      ┆ 49.693429 ┆ null  ┆ null     │
│ min        ┆ 1.0         ┆ 0.0      ┆ 1.0      ┆ … ┆ 110152    ┆ 0.0       ┆ A10   ┆ C        │
│ 25%        ┆ 224.0       ┆ 0.0      ┆ 2.0      ┆ … ┆ null      ┆ 7.925     ┆ null  ┆ null     │
│ 50%        ┆ 446.0       ┆ 0.0      ┆ 3.0      ┆ … ┆ null      ┆ 14.4542   ┆ null  ┆ null     │
│ 75%        ┆ 669.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ null      ┆ 31.0      ┆ null  ┆ null     │
│ max        ┆ 891.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ WE/P 5735 ┆ 512.3292  ┆ T     ┆ S        │
└────────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────┴──────────┘

Чтобы посчитать количество пассажирова обратимся к колонке "Pclass".

In [61]:
df['Pclass'].value_counts()

shape: (3, 2)
┌────────┬───────┐
│ Pclass ┆ count │
│ ---    ┆ ---   │
│ i64    ┆ u32   │
╞════════╪═══════╡
│ 2      ┆ 184   │
│ 1      ┆ 216   │
│ 3      ┆ 491   │
└────────┴───────┘

Необходимо вывести количество выживших мужчин и женщин на корабле, для отсортируем у кого в колонке "Survived" стоит 1 и возьмем колонку "Sex".

In [62]:
df.filter(pl.col('Survived') == 1).select(pl.col('Sex').value_counts())

shape: (2, 1)
┌────────────────┐
│ Sex            │
│ ---            │
│ struct[2]      │
╞════════════════╡
│ {"female",233} │
│ {"male",109}   │
└────────────────┘

Необходимо вывести часть таблицы с пассажирами, возраст которых больше 44 лет.

In [63]:
df.filter(pl.col('Age') > 44)

shape: (115, 12)
┌─────────────┬──────────┬────────┬──────────────────┬───┬────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name             ┆ … ┆ Ticket     ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---              ┆   ┆ ---        ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str              ┆   ┆ str        ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪══════════════════╪═══╪════════════╪═════════╪═══════╪══════════╡
│ 7           ┆ 0        ┆ 1      ┆ McCarthy, Mr.    ┆ … ┆ 17463      ┆ 51.8625 ┆ E46   ┆ S        │
│             ┆          ┆        ┆ Timothy J        ┆   ┆            ┆         ┆       ┆          │
│ 12          ┆ 1        ┆ 1      ┆ Bonnell, Miss.   ┆ … ┆ 113783     ┆ 26.55   ┆ C103  ┆ S        │
│             ┆          ┆        ┆ Elizabeth        ┆   ┆            ┆         ┆       ┆          │
│ 16          ┆ 1        ┆ 2      ┆ Hewlett, Mrs.    ┆ … ┆ 248706     ┆ 16.0    ┆ null  ┆ S        │
│             ┆          ┆        ┆ (Mary D          ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ Kingcome…        ┆   ┆            ┆         ┆       ┆          │
│ 34          ┆ 0        ┆ 2      ┆ Wheadon, Mr.     ┆ … ┆ C.A. 24579 ┆ 10.5    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Edward H         ┆   ┆            ┆         ┆       ┆          │
│ 53          ┆ 1        ┆ 1      ┆ Harper, Mrs.     ┆ … ┆ PC 17572   ┆ 76.7292 ┆ D33   ┆ C        │
│             ┆          ┆        ┆ Henry Sleeper    ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ (My…             ┆   ┆            ┆         ┆       ┆          │
│ …           ┆ …        ┆ …      ┆ …                ┆ … ┆ …          ┆ …       ┆ …     ┆ …        │
│ 858         ┆ 1        ┆ 1      ┆ Daly, Mr. Peter  ┆ … ┆ 113055     ┆ 26.55   ┆ E17   ┆ S        │
│             ┆          ┆        ┆ Denis            ┆   ┆            ┆         ┆       ┆          │
│ 863         ┆ 1        ┆ 1      ┆ Swift, Mrs.      ┆ … ┆ 17466      ┆ 25.9292 ┆ D17   ┆ S        │
│             ┆          ┆        ┆ Frederick Joel   ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ (Ma…             ┆   ┆            ┆         ┆       ┆          │
│ 872         ┆ 1        ┆ 1      ┆ Beckwith, Mrs.   ┆ … ┆ 11751      ┆ 52.5542 ┆ D35   ┆ S        │
│             ┆          ┆        ┆ Richard Leonard… ┆   ┆            ┆         ┆       ┆          │
│ 874         ┆ 0        ┆ 3      ┆ Vander Cruyssen, ┆ … ┆ 345765     ┆ 9.0     ┆ null  ┆ S        │
│             ┆          ┆        ┆ Mr. Victor       ┆   ┆            ┆         ┆       ┆          │
│ 880         ┆ 1        ┆ 1      ┆ Potter, Mrs.     ┆ … ┆ 11767      ┆ 83.1583 ┆ C50   ┆ C        │
│             ┆          ┆        ┆ Thomas Jr (Lily  ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ A…               ┆   ┆            ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴──────────────────┴───┴────────────┴─────────┴───────┴──────────┘

# Ускорение работы с pandas

Считайте датасет из файла train.csv с помощью pandas

In [64]:
import pandas as pd

df_pd = pd.read_csv("train.csv")
df_pd.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [65]:
import bottleneck as bn

mean_age = bn.nanmean(df_pd["Age"].values)
std_age = bn.nanstd(df_pd["Age"].values)

print(f"Средний возраст пассажиров: {mean_age:.2f}")
print(f"Стандартное отклонение возраста: {std_age:.2f}")

Средний возраст пассажиров: 29.70
Стандартное отклонение возраста: 14.52

Для каждого пассажира умножьте значение столбца Fare на 1.3, если класс его билета - 1 или 2, и на 1.1, если класс его билета - 3. Сохраните результаты как новый столбец Fare_new.

In [66]:
import numpy as np

df_pd["Fare_new"] = np.where(
    df_pd["Pclass"].isin([1, 2]),
    df_pd["Fare"] * 1.3,
    df_pd["Fare"] * 1.1
)

df_pd[["Pclass", "Fare", "Fare_new"]].head(10)

   Pclass     Fare  Fare_new
0       3   7.2500   7.97500
1       1  71.2833  92.66829
2       3   7.9250   8.71750
3       1  53.1000  69.03000
4       3   8.0500   8.85500
5       3   8.4583   9.30413
6       1  51.8625  67.42125
7       3  21.0750  23.18250
8       3  11.1333  12.24663
9       2  30.0708  39.09204

In [67]:
df_pd.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_new
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,7.97500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,92.66829
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,8.71750
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,69.03000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,8.85500
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,9.30413
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,67.42125
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,23.18250
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,12.24663
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,39.09204

# Оптимизация типов pandas

Считайте датасет из файла Housing.csv  с помощью pandas

In [68]:
import pandas as pd

df_pd1 = pd.read_csv("Housing.csv")
df_pd1.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished

In [69]:
print(df_pd1.describe(include="all"))


print("\nТекущие типы:")
print(df_pd1.dtypes)

               price          area    bedrooms   bathrooms     stories  \
count   5.450000e+02    545.000000  545.000000  545.000000  545.000000
unique           NaN           NaN         NaN         NaN         NaN
top              NaN           NaN         NaN         NaN         NaN
freq             NaN           NaN         NaN         NaN         NaN
mean    4.766729e+06   5150.541284    2.965138    1.286239    1.805505
std     1.870440e+06   2170.141023    0.738064    0.502470    0.867492
min     1.750000e+06   1650.000000    1.000000    1.000000    1.000000
25%     3.430000e+06   3600.000000    2.000000    1.000000    1.000000
50%     4.340000e+06   4600.000000    3.000000    1.000000    2.000000
75%     5.740000e+06   6360.000000    3.000000    2.000000    2.000000
max     1.330000e+07  16200.000000    6.000000    4.000000    4.000000

       mainroad guestroom basement hotwaterheating airconditioning  \
count       545       545      545             545             545
unique        2         2        2               2               2
top         yes        no       no              no              no
freq        468       448      354             520             373
mean        NaN       NaN      NaN             NaN             NaN
std         NaN       NaN      NaN             NaN             NaN
min         NaN       NaN      NaN             NaN             NaN
25%         NaN       NaN      NaN             NaN             NaN
50%         NaN       NaN      NaN             NaN             NaN
75%         NaN       NaN      NaN             NaN             NaN
max         NaN       NaN      NaN             NaN             NaN

           parking prefarea furnishingstatus
count   545.000000      545              545
unique         NaN        2                3
top            NaN       no   semi-furnished
freq           NaN      417              227
mean      0.693578      NaN              NaN
std       0.861586      NaN              NaN
min       0.000000      NaN              NaN
25%       0.000000      NaN              NaN
50%       0.000000      NaN              NaN
75%       1.000000      NaN              NaN
max       3.000000      NaN              NaN

Текущие типы:
price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

Комментарии:

- 'price' — float64 → можно оставить float32 (max int32: 2.10000e+09, а max цена  1.330000e+07)
- 'area' — int64 → можно перевести в int16 (max площадь 16200, а max int16 = 32k)
- 'bedrooms', 'bathrooms' — int64 → int8 (значения 0–10)
- 'stories' — int64 → int8 (значения 0–10)
- 'mainroad', 'guestroom', 'basement', 'hotwaterheating',
  'airconditioning', 'prefarea' — object, но содержат 'yes'/'no' → можно заменить на bool
- 'furnishingstatus' — object, категориальный ('furnished', 'semi-furnished', 'unfurnished') → category

In [70]:
mem_before = df_pd1.memory_usage(deep=True).sum() / 1024**2

df_opt = df_pd1.copy()

df_opt = df_opt.astype({
    "price": "float32",
    "area": "int16",
    "bedrooms": "int8",
    "bathrooms": "int8",
    "stories": "int8",
    "parking": "int8"
})

bool_cols = [
    "mainroad", "guestroom", "basement",
    "hotwaterheating", "airconditioning", "prefarea"
]
for col in bool_cols:
    df_opt[col] = df_opt[col].map({"yes": True, "no": False}).astype("bool")

df_opt["furnishingstatus"] = df_opt["furnishingstatus"].astype("category")

mem_after = df_opt.memory_usage(deep=True).sum() / 1024**2

print(f"Память до оптимизации: {mem_before:.3f} MB")
print(f"Память после оптимизации: {mem_after:.3f} MB")
print(f"Снижение потребления памяти: {(1 - mem_after / mem_before) * 100:.2f}%")


print(df_opt.dtypes)

Память до оптимизации: 0.217 MB
Память после оптимизации: 0.009 MB
Снижение потребления памяти: 95.74%
price                float32
area                   int16
bedrooms                int8
bathrooms               int8
stories                 int8
mainroad                bool
guestroom               bool
basement                bool
hotwaterheating         bool
airconditioning         bool
parking                 int8
prefarea                bool
furnishingstatus    category
dtype: object